### ISSUE TITLE
Volumes "server-data" and "server-files" are not used

### ISSUE THREAD

**Issue by m4mfr3d** [escapingnetwork/core-keeper-dedicated#48]
Hello, 
I have set up the Docker container on my Synology NAS DS923+. However, if I specify the volumes "server-data" and "server-files", these are not used. The save data is still stored in the container. 
I extracted the container and found the save files at the following path: ...\image\home\steam\core-keeper-data

I haven't had this problem with other Docker containers yet.

The permissions for the folders are correct. Otherwise I would receive an error message in the logs or the container would not be able to write the storage files into the container. 

Since I couldn't find a similar case through Google, I'm assuming it is an issue.

**Comment by arguser** [comment]
Hello @m4mfr3d I just created a server for testing this and I see the content inside the docker volumes. I'm using Docker Desktop on Windows + WSL 
![image](https://github.com/user-attachments/assets/1b0a15cc-9134-4cde-a3d5-a6d386a1c829)
![image](https://github.com/user-attachments/assets/391ed224-04db-4fc0-a12c-af6c24ffe5ac)

Maybe your system handles things differently?

**Comment by Micke90s** [comment]
@m4mfr3d Could you please post your `docker-compose.yml`?
On which host system the container is running?

**Comment by m4mfr3d** [comment]
I don't use any docker-compose.yml. 
I'm using the Container Manager on Synology DSM 7.2.1.

**Comment by Micke90s** [comment]
The Container Manager should work similar to `docker-compose.yml`. It sounds like the mapping of the docker file path and the volume is missing. 

```yaml
services:
  core-keeper:
   ...
    #This is the mapping from the volume to docker file system 
    volumes:
      - server-files:/home/steam/core-keeper-dedicated
      - server-data:/home/steam/core-keeper-data
    ...
#This are the defined volumes
volumes: 
    server-files:
    server-data:
```

I would suspect that the Container Manager has some settings for the required `server-data:/home/steam/core-keeper-data`
