### ISSUE TITLE
Access to the X11 socket

### ISSUE THREAD

**Issue by arguser** [escapingnetwork/core-keeper-dedicated#7]
> Can you expand on what you meant by the tmp mounting or give a example so others can do that fix too?

Sure! Core Keeper eventually switches to GPU rendering for generating farther away areas. In order to do this, it needs access to the X11 socket accessible inside `/tmp/.X11-unix` to access the host's X11 socket and therefore the graphics hardware. The container/server log actually warns about that particular path not being accessible otherwise.

In my docker-compose, I expose this as a volume:

```yaml
version: "3"

services:
  core-keeper:
    container_name: core-keeper
    image: escaping/core-keeper-dedicated:latest
    volumes:
      - REDACTED:/home/steam/core-keeper-dedicated
      - REDACTED:/home/steam/core-keeper-data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - WORLD_INDEX=0
      - WORLD_NAME=REDACTED
      - WORLD_SEED=0
      - GAME_ID=REDACTED
      - DATA_PATH=/home/steam/core-keeper-data
      - MAX_PLAYERS=8
    restart: unless-stopped
    stop_grace_period: 2m
```

_Originally posted by @xcjs in https://github.com/escapingnetwork/core-keeper-dedicated/issues/5#issuecomment-1186609942_
