### ISSUE TITLE
Docker Compose with Coolify

### ISSUE THREAD

**Issue by borsTiHD** [escapingnetwork/core-keeper-dedicated#70]
Hi, thank you very much for your work.
I have a question and didn't know how to address them to you.

I would like to use Coolify to manage the Docker Compose. The setup also worked, but I don't know the best way to place the `core.env` file. That's why I left out the part from the Docker Compose and wanted to use Coolify's own env management. When I started the service several times, I noticed that it was probably not being used. A new GameID is also created each time the service is started and my server name is also not used from the env, but the world seems to remain saved without any problems.

The environment variables should actually be set by Coolify, but alternatively I would create the file permanently, unfortunately I don't know where.

Can you help me?
Many thanks in advance.

**Comment by Diyagi** [comment]
Ive never used Coolify, but reading [this page](https://coolify.io/docs/knowledge-base/docker/compose/) it seems like the envs you set in the UI are kinda of set in the host and not inside the container itself, so i believe you need to map the env this container uses to envs in the host, something like this i believe:

```
services:
  dedicated:
    image: escaping/core-keeper-dedicated
    restart: always
    stop_grace_period: 2m
    ports:
      - "27020:27020/udp"
      - "27021:27021/udp"
    volumes:
      - /opt/server-data/corekeeper/server-files:/home/steam/core-keeper-dedicated
      - /opt/server-data/corekeeper/server-data:/home/steam/core-keeper-data
    environment:
      TZ: ${UI_TZ}
      PUID: ${UI_PUID}
      PGID: ${UI_GUID}
      WORLD_INDEX: ${UI_WORLD_INDEX}
      WORLD_NAME: ${UI_WORLD_NAME}
      WORLD_SEED: ${UI_WORLD_SEED}
      WORLD_MODE: ${UI_WORLD_MODE}
      GAME_ID: ${UI_GAME_ID}
      SERVER_IP: ${UI_SERVER_IP}
      SERVER_PORT: ${UI_SERVER_PORT}
```

The docs says it will see those envs (like `UI_GAME_ID`} and will populate its UI so you can set its value.
I dont know if im right or if this is the best way of doing this because i have never used Coolify, but i hope it helps.
