### ISSUE TITLE
Using relative volume paths instead of named volumes

### ISSUE THREAD

**Issue by IcelandicIcecream** [escapingnetwork/core-keeper-dedicated#71]
Hey guys! I remember I was pretty confused with volumes when I first started my server. Like whether it was working or not and how to back them up and etc. I definitely feel like using or at least encouraging relative paths would be better instead of defaulting to named volumes in the readme. So everything is accessible within 1 directory. 

This technically wouldn't break anything I think.

```
services:
  core-keeper:
    container_name: core-keeper-dedicated
    image: escaping/core-keeper-dedicated
    volumes:
      - ./server-files:/home/steam/core-keeper-dedicated ## instead of server-files:...
      - ./server-data:/home/steam/core-keeper-data ## instead of server-data:....
    env_file:
      - ./core.env
    restart: always
    stop_grace_period: 2m
```

Not sure if I'm missing anything or if there was a specific reason for named volumes.
