### ISSUE TITLE
No saves present after container start with docker compose

### ISSUE THREAD

**Issue by koudy2** [escapingnetwork/core-keeper-dedicated#82]
Hello, i am trying to figure out missing save files. I went over other issues (closed ones) but nothing seems to be working.
Server is running on Oracle cloud.
Configs are as follows
core.env

```
PUID=1002
PGID=1002
ARM64_DEVICE=adlink
USE_DEPOT_DOWNLOADER=false
WORLD_INDEX=0
WORLD_NAME="Core Keeper Server"
WORLD_SEED=0
WORLD_MODE=0
GAME_ID=""
DATA_PATH="/home/steam/core-keeper-data"
MAX_PLAYERS=10
SEASON=""
SERVER_IP=""
SERVER_PORT="27015"
```

docker-compose.yml

```
services:
  core-keeper:
    container_name: core-keeper-dedicated
    image: escaping/core-keeper-dedicated
    ports:
      - "27015:27015/udp"
    volumes:
      - /home/steam/servers/core_keeper/server-files:/home/steam/core-keeper-dedicated
      - /home/steam/servers/core_keeper/server-data:/home/steam/core-keeper-data
    restart: unless-stopped
    env_file:
      - path: core.env
        required: false
    stop_grace_period: 2m
volumes:
  server-files:
  server-data:
```

I noticed few things. After server starts, seed is always the same - `core-keeper-dedicated  | Hashed string seed 0 -> 4108050209`
Save files do not exist (this is run on the host system)

```
$ ls server*
server-data:
Admins.json  Admins.json.pugbackup  modloader  mods  ServerConfig.json  ServerConfig.json.pugbackup

server-files:
CoreKeeperServer  CoreKeeperServer_Data  GameID.txt  _launch.sh  launch.sh  legal  linux64  logs  _readme.sh  README.txt  steamapps  steamclient.so  UnityPlayer.so
```
Saves also don't exist inside the container :
```
root@3db140720ed6:/home/steam# ls /home/steam/.config/Pugstorm/Core\ Keeper/DedicatedServer
ls: cannot access '/home/steam/.config/Pugstorm/Core Keeper/DedicatedServer': No such file or directory
root@3db140720ed6:/home/steam# ls /home/steam/.config/Pugstorm/Core\ Keeper/
ls: cannot access '/home/steam/.config/Pugstorm/Core Keeper/': No such file or directory
root@3db140720ed6:/home/steam# ls /home/steam/.config/Pugstorm/
ls: cannot access '/home/steam/.config/Pugstorm/': No such file or directory
root@3db140720ed6:/home/steam# ls /home/steam/.config/
unity3d
```

Thanks for any advices how to proceed with this.
