### ISSUE TITLE
Connection time out - joining from Steam

### ISSUE THREAD

**Issue by nevaran** [escapingnetwork/core-keeper-dedicated#88]
Theres a game ID that gets generated but when attempting to connect it times out. Logs dont seem to be saying anything useful to me.
Connection attempt is on a local network, different subnet.
Nothing gets blocked, and nothing gets established as a connection except for one going to a valve corporation IP with destination port 27019

Compose:
```
services:
  core-keeper:
    container_name: core-keeper-dedicated
    image: escaping/core-keeper-dedicated
    user: "1000:997"
    ports:
      - "$SERVER_PORT:$SERVER_PORT/udp"
    volumes:
      - ./server-files:/home/steam/core-keeper-dedicated
      - ./server-data:/home/steam/core-keeper-data
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    stop_grace_period: 2m
volumes:
    server-files:
    server-data:
```

.env
```
PUID=1000
PGID=997
ARM64_DEVICE=generic
USE_DEPOT_DOWNLOADER=false
WORLD_INDEX=1
WORLD_NAME="Core Keeper Test Server"
WORLD_SEED=""
WORLD_MODE=0
GAME_ID=""
DATA_PATH="${STEAMAPPDATADIR:-/home/steam/core-keeper-data}"
MAX_PLAYERS=10
SEASON=""
SERVER_IP=""
SERVER_PORT="27015"
DISCORD_WEBHOOK_URL=""
# Player Join
#DISCORD_PLAYER_JOIN_ENABLED=true
#DISCORD_PLAYER_JOIN_MESSAGE="$${char_name} ($${steamid}) has joined the server."
#DISCORD_PLAYER_JOIN_TITLE="Player Joined"
#DISCORD_PLAYER_JOIN_COLOR="47456"
# Player Leave
#DISCORD_PLAYER_LEAVE_ENABLED=true
#DISCORD_PLAYER_LEAVE_MESSAGE="$${char_name} ($${steamid}) has disconnected. Reason: $${reason}."
#DISCORD_PLAYER_LEAVE_TITLE="Player Left"
#DISCORD_PLAYER_LEAVE_COLOR="11477760"
# Server Start
DISCORD_SERVER_START_ENABLED=true
DISCORD_SERVER_START_MESSAGE="**World:** $${world_name}\n**GameID:** $${gameid}"
DISCORD_SERVER_START_TITLE="Server Started"
DISCORD_SERVER_START_COLOR="2013440"
# Server Stop
DISCORD_SERVER_STOP_ENABLED=true
DISCORD_SERVER_STOP_MESSAGE=""
DISCORD_SERVER_STOP_TITLE="Server Stopped"
DISCORD_SERVER_STOP_COLOR="12779520"
# Mods
MODS_ENABLED=false
MODIO_API_KEY=""
MODIO_API_URL=""
MODS=""
```

**logs when docker up -d uploaded as file**

[_core-keeper-dedicated_logs.txt](https://github.com/user-attachments/files/20125536/_core-keeper-dedicated_logs.txt)
